# Generated by Django 3.2.9 on 2022-01-14 08:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('intervenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminTache.intervenant')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_heure_debut', models.DateField(verbose_name=datetime.datetime(2022, 1, 14, 8, 23, 11, 246276, tzinfo=utc))),
                ('duree', models.IntegerField(default=1)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminTache.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('duree', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=200)),
                ('faite', models.BooleanField(default=False)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminTache.seance')),
            ],
        ),
    ]
