# Generated by Django 3.2.9 on 2022-01-14 08:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adminTache', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='date_heure_debut',
            field=models.DateField(verbose_name=datetime.datetime(2022, 1, 14, 8, 38, 52, 15985, tzinfo=utc)),
        ),
    ]
