# Generated by Django 3.2.9 on 2022-01-14 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adminTache', '0002_alter_seance_date_heure_debut'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='titre',
            field=models.CharField(default='IPYT011', max_length=7),
        ),
        migrations.AddField(
            model_name='tache',
            name='titre',
            field=models.CharField(default='Faire une pause', max_length=50),
        ),
        migrations.AlterField(
            model_name='seance',
            name='date_heure_debut',
            field=models.DateField(verbose_name=datetime.datetime(2022, 1, 14, 8, 55, 46, 1040, tzinfo=utc)),
        ),
    ]
