# Generated by Django 3.2.9 on 2022-01-14 09:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adminTache', '0007_alter_seance_date_heure_debut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='date_heure_debut',
            field=models.DateField(default=datetime.datetime(2022, 1, 14, 9, 30, 18, 905720, tzinfo=utc)),
        ),
    ]
