# Generated by Django 3.2.9 on 2022-02-11 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('CONGE', 'FINI'), ('EST MALADE', 'EST MALADE'), ('VIENS DARRIVER', 'VIENS DARRIVER'), ('NORMAL', 'NORMAL'), ('ABSENT', 'ABSENT')], default='NORMAL', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(default='Tache sans nom', max_length=250)),
                ('date_livraison', models.DateField()),
                ('status', models.CharField(choices=[('FINI', 'FINI'), ('EN COURS', 'EN COURS'), ('A COMMENCER', 'A COMMENCER')], default='A COMMENCER', max_length=200)),
                ('etat_avancement', models.IntegerField(default=1)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=200)),
                ('priorite', models.IntegerField(default=1)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('FINI', 'FINI'), ('EN COURS', 'EN COURS'), ('A COMMENCER', 'A COMMENCER')], default='A COMMENCER', max_length=200)),
                ('etat_avancement', models.IntegerField(default=1)),
                ('personne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.personne')),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.projet')),
                ('tacheParente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tache')),
            ],
        ),
    ]
