# Generated by Django 3.2.9 on 2022-04-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220412_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='description',
            field=models.CharField(default='Tache sans description', max_length=200),
        ),
    ]
